buildVariable: false
category:
- SERIF
familyName: Noto Serif Ottoman Siyaq
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifOttomanSiyaq.glyphs
